### ISSUE TITLE
Test on the relation between event and branches ignore in a workflow

### ISSUE THREAD

**Issue by hermitkim1** [cloud-barista/poc-cicd-spider#9]

**Comment by hermitkim1** [comment]
[테스트 결과] 
CI를 위한 워크플로우는 아래와 같은 이벤트를 적용할 필요가 있음
```yaml
on:
  push:
    branches-ignore:
    - main
    - master
  pull-request:
```
